### PR TITLE
add: Fix/improve pre commit config and docs

### PR DESCRIPTION
**Pull request by fellipeh**
## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by sthirugn** [comment]
I tested this locally and it found a lot of things to improve int he code with `pre-commit run --all-files` :+1:

**Comment by sthirugn** [comment]
Asking @vkrizan to review as he has worked with several python projects in the past and may have some feedbak.

**Review by vkrizan — APPROVED** [review]
LGTM.

I haven't tried the configuration. It might need a first run to update the files.

**Comment by sthirugn** [comment]
@fellipeh do you want to do the first run and update the files in this PR or a new PR?

**Comment by fellipeh** [comment]
@sthirugn I agree with you.. let run the files in other PR.

**Pull request merged**
