### PR TITLE
ubi8-minimal and no s2i

### PR DESCRIPTION
**Pull request by petrblaho**
## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by petrblaho** [comment]
DRFT-1234

**Comment by petrblaho** [comment]
Needs https://github.com/RedHatInsights/drift-backend/pull/367 merged and then rebase

**Review by fellipeh — APPROVED** [review]
lgtm

**Pull request merged**
