### PR TITLE
switch from pipenv to poetry

### PR DESCRIPTION
**Pull request by petrblaho**
`pipenv` proved itself unusable over the time.

This PR switched the project over to the usage of `poetry`.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by petrblaho** [comment]
@radohanculak ^

**Review by fellipeh — APPROVED** [review]
LGTM. Nice Petr!!

**Review by CodeHeeler — APPROVED** [review]
LGTM, thanks for taking care of this! Poetry does sound like the better option.

**Pull request merged**
