### PR TITLE
DRFT-714 Change the end to call system-baseline endpoint

### PR DESCRIPTION
**Pull request by fellipeh**
https://github.com/RedHatInsights/kerlescan/pull/44
^^^
**NEED to be merged before this PR.**

This PR create a new `/admin/status` endpoint into systema-baseline, and
make drift-backend to call this new enpoint

Signed-off-by: Fellipe Henrique <fpedrosa@redhat.com>

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by sthirugn** [comment]
@fellipeh looks great, can you update the kerlescan tag too to 0.76?

**Comment by fellipeh** [comment]
It's failing because when I sent this PR, I sent a new PR for kerlescan.. now we get the new tag on kerlescan.. I'll update the tag here.

**Comment by jpramos123** [comment]
How/where do we define env variables on Travis?

**Review by CodeHeeler — APPROVED** [review]
LGTM, thank you so much!

**Pull request merged**
