### PR TITLE
DRFT-129 Changes comparison state when obfuscated values are present

### PR DESCRIPTION
**Pull request by petrblaho**
Fact state will be changed to COMPARISON_INCOMPLETE_DATA_OBFUSCATED when
one or more of compared values are obfuscated.

### CODE REVIEW

**Comment by petrblaho** [comment]
https://issues.redhat.com/browse/DRFT-129

**Comment by petrblaho** [comment]
Needs https://github.com/RedHatInsights/kerlescan/pull/8 merged, new version of kerlescan tagged and updated dependencies here.

**Comment by CodeHeeler** [comment]
This looks great, once you tag kerlescan and update that, happy to approve.

**Comment by petrblaho** [comment]
@CodeHeeler thanks. Deps are updated, I also found a test that needed an update.

**Review by CodeHeeler — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
