### PR TITLE
Adds obfuscated values filtering

### PR DESCRIPTION
**Pull request by petrblaho**

### CODE REVIEW

**Comment by petrblaho** [comment]
https://github.com/RedHatInsights/kerlescan/pull/7

**Comment by petrblaho** [comment]
https://issues.redhat.com/browse/DRFT-30

**Comment by petrblaho** [comment]
@eherget

**Comment by petrblaho** [comment]
I will update PR with dependency change when https://github.com/RedHatInsights/kerlescan/pull/7 is merged and new kerlescan version is tagged.

**Review by eherget — APPROVED** [review]
This looks good. We will add unit tests specific to obfuscated values in a Jira task.

**Comment by petrblaho** [comment]
> This looks good. We will add unit tests specific to obfuscated values in a Jira task.
https://issues.redhat.com/browse/DRFT-120

**Pull request merged**
