### PR TITLE
[NOMERGE] post test results script

### PR DESCRIPTION
**Pull request by lina-is-here**
This is a test of a new step in the CI - posting results.
Please ignore this and do not merge.

### CODE REVIEW

**Comment by lina-is-here** [comment]
first comment

**Comment by lina-is-here** [comment]
comment

**Comment by InsightsDroid** [comment]
test comment

**Comment by lina-is-here** [comment]
4ac5a98c-84d9-48e4-9af9-04cc3064b861 65eda572-331b-435b-bed4-1584c3516576

**Comment by lina-is-here** [comment]
4ac5a98c-84d9-48e4-9af9-04cc3064b861 65eda572-331b-435b-bed4-1584c3516576

**Comment by InsightsDroid** [comment]
Test results are available in Ibutsu. The test run IDs are 51dd97c3-136e-418f-9a74-ce5c78d683cc 74614655-c29d-414c-bb03-6639f7296cb8.

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu). The test run IDs are:
7b27fce5-c9a2-4f81-b431-fa07b682f358
bca80523-1471-4a29-bc05-0bec42c3f236

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
11a037aa-1be3-4849-acb6-42d1c614594f
4a134e35-a995-4b18-a11f-121cf3f171ef

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
5bf38517-ab40-4c2f-8f35-da1c40997912
83320626-c9eb-47b0-bcc0-7afeff259c3b

**Pull request closed without merging**
