### PR TITLE
DRFT-199 Adds audit logging

### PR DESCRIPTION
**Pull request by petrblaho**
Use it as `logger.audit("message")`
to see output as `[2021-02-18 15:29:43 +0000] [29] [AUDIT] message`.## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [x] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by petrblaho** [comment]
https://issues.redhat.com/browse/DRFT-199

**Comment by petrblaho** [comment]
Depends on new kerlescan version with https://github.com/RedHatInsights/kerlescan/pull/14

**Review by CodeHeeler — APPROVED** [review]
Once you update to the new version of kerlescan, looks good to me here.  Thanks!

**Comment by petrblaho** [comment]
@CodeHeeler thank you....

I force pushed new version to solve flake8 and black issues

**Comment by petrblaho** [comment]
Updated to reflect after review changes in https://github.com/RedHatInsights/kerlescan/pull/14

**Review by CodeHeeler — APPROVED** [review]
Once the new kerlescan is tagged and added, I think this will be ready to go.  Thanks!

**Pull request merged**
