### PR TITLE
Add ImageStream and update build config

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by beav** [comment]
@ehelms this had a yaml fail that was hidden by the test fail gore:

```
0.18s$ yamllint openshift/
openshift/deploy.yml
  21:101    error    line too long (103 > 100 characters)  (line-length)
The command "yamllint openshift/" exited with 1.
```

**Comment by ehelms** [comment]
Re-factored to a role to make it cleaner and fix the lenght issue.

**Comment by beav** [comment]
https://github.com/RedHatInsights/drift-backend/pull/64 should fix the tests, travis is being slow today

**Comment by ehelms** [comment]
@beav  Looks like this is passing now, thanks for fixing the unit test

**Pull request merged**
